---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ofluxstage
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/VLXMDE/ofluxstage
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ofluxstage
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: ofluxstage
